"use client";

import { useState } from "react";
import { eventInputSchema } from "@/lib/validations/event";
import {
  createEvent,
  generateEventContent,
  updateEvent,
  type EventFormData,
} from "@/lib/api-client";
import type { SerializedEvent } from "@/lib/models/Event";
import { Alert } from "@/components/Alert";
import { Loader } from "@/components/Loader";

interface EventFormProps {
  mode: "create" | "edit";
  initialData?: SerializedEvent;
  onSuccess: (event: SerializedEvent) => void;
}

type FieldErrors = Partial<Record<keyof EventFormData, string>>;

const emptyForm: EventFormData = {
  eventName: "",
  eventDate: "",
  speakerName: "",
  speakerDesignation: "",
  description: "",
  speakerIntro: "",
};

function toFormData(event?: SerializedEvent): EventFormData {
  if (!event) return emptyForm;
  const date = new Date(event.eventDate);
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  return {
    eventName: event.eventName,
    eventDate: `${yyyy}-${mm}-${dd}`,
    speakerName: event.speakerName,
    speakerDesignation: event.speakerDesignation,
    description: event.description,
    speakerIntro: event.speakerIntro,
  };
}

function validateClient(form: EventFormData): FieldErrors {
  const result = eventInputSchema.safeParse(form);
  if (result.success) return {};

  const errors: FieldErrors = {};
  result.error.errors.forEach((issue) => {
    const field = issue.path[0] as keyof EventFormData;
    if (!errors[field]) {
      errors[field] = issue.message;
    }
  });
  return errors;
}

export function EventForm({ mode, initialData, onSuccess }: EventFormProps) {
  const [form, setForm] = useState<EventFormData>(() => toFormData(initialData));
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({});
  const [formError, setFormError] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const updateField = (field: keyof EventFormData, value: string) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    setFieldErrors((prev) => ({ ...prev, [field]: undefined }));
    setFormError("");
    setSuccessMessage("");
  };

  const handleGenerateAI = async () => {
    const clientErrors = validateClient(form);
    if (Object.keys(clientErrors).length > 0) {
      setFieldErrors(clientErrors);
      setFormError("Please fix the required fields before generating AI content.");
      return;
    }

    setIsGenerating(true);
    setFormError("");

    const result = await generateEventContent(form);

    setIsGenerating(false);

    if (!result.description) {
      setFormError(result.message || "Failed to generate AI content.");
      return;
    }

    setForm((prev) => ({
      ...prev,
      description: result.description,
      speakerIntro: result.speakerIntro,
    }));
    setSuccessMessage("Content generated by Gemini AI. Review before saving.");
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError("");
    setSuccessMessage("");

    const clientErrors = validateClient(form);
    if (Object.keys(clientErrors).length > 0) {
      setFieldErrors(clientErrors);
      return;
    }

    setIsSubmitting(true);

    const result =
      mode === "create"
        ? await createEvent(form)
        : await updateEvent(initialData!.id, form);

    setIsSubmitting(false);

    if (result.errors?.length) {
      const apiErrors: FieldErrors = {};
      result.errors.forEach((err) => {
        const key = err.field as keyof EventFormData;
        if (!apiErrors[key]) apiErrors[key] = err.message;
      });
      setFieldErrors(apiErrors);
      setFormError(result.message || "Please correct the errors below.");
      return;
    }

    if (!result.event?.id) {
      setFormError(result.message || "Something went wrong. Please try again.");
      return;
    }

    if (mode === "create") {
      setSuccessMessage("Event created successfully!");
      setForm(emptyForm);
      setTimeout(() => onSuccess(result.event), 800);
    } else {
      onSuccess(result.event);
    }
  };

  const inputClass = (field: keyof EventFormData) =>
    `w-full rounded-lg border px-3 py-2.5 text-sm outline-none transition focus:ring-2 focus:ring-primary/20 ${
      fieldErrors[field]
        ? "border-red-400 bg-red-50 focus:border-red-400"
        : "border-border bg-white focus:border-primary"
    }`;

  return (
    <form onSubmit={handleSubmit} className="space-y-6" noValidate>
      {successMessage && <Alert variant="success" message={successMessage} />}
      {formError && <Alert variant="error" message={formError} />}

      <div className="grid gap-5 sm:grid-cols-2">
        <div className="sm:col-span-2">
          <label htmlFor="eventName" className="mb-1.5 block text-sm font-medium">
            Event Name <span className="text-danger">*</span>
          </label>
          <input
            id="eventName"
            type="text"
            value={form.eventName}
            onChange={(e) => updateField("eventName", e.target.value)}
            placeholder="Advances in Fetal Medicine"
            className={inputClass("eventName")}
          />
          {fieldErrors.eventName && (
            <p className="mt-1 text-xs text-danger">{fieldErrors.eventName}</p>
          )}
        </div>

        <div>
          <label htmlFor="eventDate" className="mb-1.5 block text-sm font-medium">
            Event Date <span className="text-danger">*</span>
          </label>
          <input
            id="eventDate"
            type="date"
            value={form.eventDate}
            onChange={(e) => updateField("eventDate", e.target.value)}
            className={inputClass("eventDate")}
          />
          {fieldErrors.eventDate && (
            <p className="mt-1 text-xs text-danger">{fieldErrors.eventDate}</p>
          )}
        </div>

        <div>
          <label htmlFor="speakerName" className="mb-1.5 block text-sm font-medium">
            Speaker Name <span className="text-danger">*</span>
          </label>
          <input
            id="speakerName"
            type="text"
            value={form.speakerName}
            onChange={(e) => updateField("speakerName", e.target.value)}
            placeholder="Dr. Jane Smith"
            className={inputClass("speakerName")}
          />
          {fieldErrors.speakerName && (
            <p className="mt-1 text-xs text-danger">{fieldErrors.speakerName}</p>
          )}
        </div>

        <div className="sm:col-span-2">
          <label
            htmlFor="speakerDesignation"
            className="mb-1.5 block text-sm font-medium"
          >
            Speaker Designation <span className="text-danger">*</span>
          </label>
          <input
            id="speakerDesignation"
            type="text"
            value={form.speakerDesignation}
            onChange={(e) => updateField("speakerDesignation", e.target.value)}
            placeholder="Senior Consultant, ABC Hospital"
            className={inputClass("speakerDesignation")}
          />
          {fieldErrors.speakerDesignation && (
            <p className="mt-1 text-xs text-danger">
              {fieldErrors.speakerDesignation}
            </p>
          )}
        </div>
      </div>

      <div className="rounded-xl border border-border bg-background p-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <p className="text-sm font-medium text-foreground">AI Content (Bonus)</p>
            <p className="text-xs text-muted">
              Generate event description and speaker introduction using Gemini AI
            </p>
          </div>
          <button
            type="button"
            onClick={handleGenerateAI}
            disabled={isGenerating || isSubmitting}
            className="rounded-lg border border-primary bg-white px-4 py-2 text-sm font-medium text-primary transition hover:bg-blue-50 disabled:opacity-50"
          >
            {isGenerating ? <Loader inline /> : "✨ Generate with AI"}
          </button>
        </div>

        {(form.description || form.speakerIntro) && (
          <div className="mt-4 space-y-4">
            {form.description && (
              <div>
                <label className="mb-1 block text-xs font-medium text-muted">
                  Event Description
                </label>
                <textarea
                  value={form.description}
                  onChange={(e) => updateField("description", e.target.value)}
                  rows={5}
                  className="w-full rounded-lg border border-border bg-white px-3 py-2 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                />
              </div>
            )}
            {form.speakerIntro && (
              <div>
                <label className="mb-1 block text-xs font-medium text-muted">
                  Speaker Introduction
                </label>
                <textarea
                  value={form.speakerIntro}
                  onChange={(e) => updateField("speakerIntro", e.target.value)}
                  rows={4}
                  className="w-full rounded-lg border border-border bg-white px-3 py-2 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"
                />
              </div>
            )}
          </div>
        )}
      </div>

      <div className="flex flex-wrap gap-3">
        <button
          type="submit"
          disabled={isSubmitting}
          className="rounded-lg bg-primary px-6 py-2.5 text-sm font-medium text-white transition hover:bg-[var(--primary-hover)] disabled:opacity-50"
        >
          {isSubmitting
            ? mode === "create"
              ? "Creating..."
              : "Saving..."
            : mode === "create"
              ? "Create Event"
              : "Save Changes"}
        </button>
      </div>
    </form>
  );
}
